# Usa gli IP Tailscale (100.x.x.x) dei tuoi server
# Li trovi con: tailscale status

[webservers]
# 100.64.0.1   # web01
# 100.64.0.2   # web02

[dbservers]
# 100.64.0.10  # db01
[test]
10.0.0.13  # db01
10.0.10.14


# Gruppo che include tutti i server
[all_servers:children]
webservers
dbservers
test
[all:vars]
ansible_user=matteo
ansible_become=true
ansible_ssh_private_key_file=~/.ssh/id_ed25519
